GET http://localhost:8080/inventory/ HTTP/1.1

###

GET http://localhost:8080/inventory/670480c7-ffab-42cf-929f-9a6ebcad3216 HTTP/1.1

###

POST http://localhost:8080/inventory HTTP/1.1
content-type: application/json

{
    "customer": "c9094c97-69b6-4f61-ab4c-288840db2060",
	"product": ,
	"quantity": ,
	"unit_of_measure": ,
}

###

PUT http://localhost:8080/inventory/670480c7-ffab-42cf-929f-9a6ebcad3216 HTTP/1.1
content-type: application/json

{
    "name": "laranja"
}