GET http://localhost:8080/inventory/ HTTP/1.1

###

GET http://localhost:8080/inventory/670480c7-ffab-42cf-929f-9a6ebcad3216 HTTP/1.1

###

POST http://localhost:8080/inventory HTTP/1.1
content-type: application/json

{
    "customer": "c9094c97-69b6-4f61-ab4c-288840db2060",
	"product": "627e8364-992c-426c-827e-90f9fe830852",
	"quantity": 20,
	"unit_of_measure": "aacb8688-ae01-4110-8909-665dd7589a1a"
}

###

PUT http://localhost:8080/inventory/670480c7-ffab-42cf-929f-9a6ebcad3216 HTTP/1.1
content-type: application/json

{
    "name": "laranja"
}