GET http://localhost:8080/baseproduct/ HTTP/1.1

###

GET http://localhost:8080/baseproduct/670480c7-ffab-42cf-929f-9a6ebcad3216 HTTP/1.1

###

POST http://localhost:8080/baseproduct HTTP/1.1
content-type: application/json

{
    "name": "abacaxi"
}

###

PUT http://localhost:8080/baseproduct/670480c7-ffab-42cf-929f-9a6ebcad3216 HTTP/1.1
content-type: application/json

{
    "name": "laranja"
}

###

DELETE http://localhost:8080/baseproduct/678f7fa4-f976-4d3d-be99-d0f7b5b133d3 HTTP/1.1
content-type: application/json