GET http://localhost:8080/product/ HTTP/1.1

###

GET http://localhost:8080/product/627e8364-992c-426c-827e-90f9fe830852 HTTP/1.1

###

POST http://localhost:8080/product HTTP/1.1
content-type: application/json

{
	"name": "maça",
	"base_product": "670480c7-ffab-42cf-929f-9a6ebcad3216"
}

###

PUT http://localhost:8080/product/670480c7-ffab-42cf-929f-9a6ebcad3216 HTTP/1.1
content-type: application/json

{
	"name": "lima",
	"base_product": "670480c7-ffab-42cf-929f-9a6ebcad3216",
}

###

DELETE http://localhost:8080/product/c50e5887-c439-4e82-bf49-e9a80b0dc533