GET http://localhost:8080/user/ HTTP/1.1

###

GET http://localhost:8080/user/2cd50e58-8ee8-454d-9cb1-4ea1d5a8cbf6 HTTP/1.1

###

POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "first_name": "buyer",
	"last_name": "andrade",
	"address": "rua tal",
	"phone": "61999999999",
	"email": "filipe.engenharia42@gmail.com",
	"latitude": -12.123123,
	"longitude": -47.123123,
	"roles": ["buyer"]
}

###

PUT http://localhost:8080/user/d1909755-a98b-47dc-86bb-03661ffe1918 HTTP/1.1
content-type: application/json

{
    "first_name": "filipe",
	"last_name": "andrade",
	"address": "rua tal 2222222222",
	"phone": "61888887777",
	"email": "casdf@gmail.com",
	"latitude": -20.123456,
	"longitude": -40.123456,
	"roles": ["producer"]
}

###

DELETE http://localhost:8080/user/4cc4a96a-7780-4ae2-90a8-94268d4565b1 HTTP/1.1